// Hand-maintained fallback for dynamic import over shared/data-grid/examples.
// Turbopack cannot statically analyze a context module built from a variable path
// segment when the target files are 'use client' components consumed from a Server
// Component (RSC boundary detection leaks into the server compile graph). Keyed by
// manifest.sourceFile (not id) since several ids share one source file.
import type { ComponentType } from 'react'

export const exampleModules: Record<string, () => Promise<Record<string, ComponentType>>> = {
	'components/base/column-visibility.tsx': () => import('./components/base/column-visibility'),
	'components/base/editing.tsx': () => import('./components/base/editing'),
	'components/base/filtering.tsx': () => import('./components/base/filtering'),
	'components/base/full.tsx': () => import('./components/base/full'),
	'components/base/inline.tsx': () => import('./components/base/inline'),
	'components/base/plain.tsx': () => import('./components/base/plain'),
	'components/base/selection.tsx': () => import('./components/base/selection'),
	'components/base/sorting.tsx': () => import('./components/base/sorting'),
	'components/base/sticky.tsx': () => import('./components/base/sticky'),
	'components/cell-types.tsx': () => import('./components/cell-types'),
	'components/column-helper.tsx': () => import('./components/column-helper'),
	'components/column-helper-registered.tsx': () => import('./components/column-helper-registered'),
	'components/column-pinning.tsx': () => import('./components/column-pinning'),
	'components/column-visibility.tsx': () => import('./components/column-visibility'),
	'components/columns/combined.tsx': () => import('./components/columns/combined'),
	'components/columns/resizing-on-change.tsx': () => import('./components/columns/resizing-on-change'),
	'components/columns/resizing-on-end.tsx': () => import('./components/columns/resizing-on-end'),
	'components/controlled-state.tsx': () => import('./components/controlled-state'),
	'components/creating/CreatingModalExample.tsx': () => import('./components/creating/CreatingModalExample'),
	'components/creating/CreatingPinRowExample.tsx': () => import('./components/creating/CreatingPinRowExample'),
	'components/creating/CreatingRowExample.tsx': () => import('./components/creating/CreatingRowExample'),
	'components/creating/CreatingValidationExample.tsx': () => import('./components/creating/CreatingValidationExample'),
	'components/crud/CrudClientExample.tsx': () => import('./components/crud/CrudClientExample'),
	'components/custom-cell-currency.tsx': () => import('./components/custom-cell-currency'),
	'components/custom-cell-progress.tsx': () => import('./components/custom-cell-progress'),
	'components/custom-cell-types.tsx': () => import('./components/custom-cell-types'),
	'components/custom-cell-user.tsx': () => import('./components/custom-cell-user'),
	'components/date-cell.tsx': () => import('./components/date-cell'),
	'components/default-options.tsx': () => import('./components/default-options'),
	'components/delete-confirmation.tsx': () => import('./components/delete-confirmation'),
	'components/editing/EditingValidationExample.tsx': () => import('./components/editing/EditingValidationExample'),
	'components/expanding/controlled.tsx': () => import('./components/expanding/controlled'),
	'components/expanding/sub-content.tsx': () => import('./components/expanding/sub-content'),
	'components/expanding/tree.tsx': () => import('./components/expanding/tree'),
	'components/fallbacks.tsx': () => import('./components/fallbacks'),
	'components/filter-chips.tsx': () => import('./components/filter-chips'),
	'components/filter-date-range.tsx': () => import('./components/filter-date-range'),
	'components/filter-multi-value.tsx': () => import('./components/filter-multi-value'),
	'components/filter-operators-between-inputs.tsx': () => import('./components/filter-operators-between-inputs'),
	'components/filter-operators-between-slider.tsx': () => import('./components/filter-operators-between-slider'),
	'components/filter-operators-date-between.tsx': () => import('./components/filter-operators-date-between'),
	'components/filter-operators-date.tsx': () => import('./components/filter-operators-date'),
	'components/filter-operators-number.tsx': () => import('./components/filter-operators-number'),
	'components/filter-operators-text.tsx': () => import('./components/filter-operators-text'),
	'components/filter-panel.tsx': () => import('./components/filter-panel'),
	'components/filter-popover.tsx': () => import('./components/filter-popover'),
	'components/global-filtering.tsx': () => import('./components/global-filtering'),
	'components/infinite-scroll/auto.tsx': () => import('./components/infinite-scroll/auto'),
	'components/infinite-scroll/manual.tsx': () => import('./components/infinite-scroll/manual'),
	'components/infinite-scroll/reset-on-query.tsx': () => import('./components/infinite-scroll/reset-on-query'),
	'components/infinite-scroll/virtualized.tsx': () => import('./components/infinite-scroll/virtualized'),
	'components/pagination-variants.tsx': () => import('./components/pagination-variants'),
	'components/row-pinning/sticky-header.tsx': () => import('./components/row-pinning/sticky-header'),
	'components/production/ProductionExample.tsx': () => import('./components/production/ProductionExample'),
	'components/production/ProductionFeedExample.tsx': () => import('./components/production/ProductionFeedExample'),
	'components/selection-bar-inline.tsx': () => import('./components/selection-bar-inline'),
	'components/selection-bar.tsx': () => import('./components/selection-bar'),
	'components/server-data.tsx': () => import('./components/server-data'),
	'components/sort-toolbar.tsx': () => import('./components/sort-toolbar'),
	'components/sorting.tsx': () => import('./components/sorting'),
	'components/state-persistence.tsx': () => import('./components/state-persistence'),
	'components/virtualized.tsx': () => import('./components/virtualized'),
}
